// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: progress-tracker.proto

package com.distilled.progress;

public interface ProgressUpdateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:progress.ProgressUpdateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string student_id = 1;</code>
   */
  java.lang.String getStudentId();
  /**
   * <code>string student_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getStudentIdBytes();

  /**
   * <code>string course_id = 2;</code>
   */
  java.lang.String getCourseId();
  /**
   * <code>string course_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getCourseIdBytes();

  /**
   * <code>string module_name = 3;</code>
   */
  java.lang.String getModuleName();
  /**
   * <code>string module_name = 3;</code>
   */
  com.google.protobuf.ByteString
      getModuleNameBytes();

  /**
   * <code>float progress_percent = 4;</code>
   */
  float getProgressPercent();
}
