// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: progress-tracker.proto

package com.distilled.progress;

public interface ProgressResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:progress.ProgressResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float percent = 1;</code>
   */
  float getPercent();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
