// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: progress-tracker.proto

package com.distilled.progress;

/**
 * <pre>
 * Message sent from server back to client after processing the stream
 * </pre>
 *
 * Protobuf type {@code progress.UpdateSummaryResponse}
 */
public  final class UpdateSummaryResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:progress.UpdateSummaryResponse)
    UpdateSummaryResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UpdateSummaryResponse.newBuilder() to construct.
  private UpdateSummaryResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UpdateSummaryResponse() {
    updatesProcessed_ = 0;
    latestProgressPercent_ = 0F;
    message_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UpdateSummaryResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            updatesProcessed_ = input.readInt32();
            break;
          }
          case 21: {

            latestProgressPercent_ = input.readFloat();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            message_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.distilled.progress.ProgressTrackerProto.internal_static_progress_UpdateSummaryResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.distilled.progress.ProgressTrackerProto.internal_static_progress_UpdateSummaryResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.distilled.progress.UpdateSummaryResponse.class, com.distilled.progress.UpdateSummaryResponse.Builder.class);
  }

  public static final int UPDATES_PROCESSED_FIELD_NUMBER = 1;
  private int updatesProcessed_;
  /**
   * <code>int32 updates_processed = 1;</code>
   */
  public int getUpdatesProcessed() {
    return updatesProcessed_;
  }

  public static final int LATEST_PROGRESS_PERCENT_FIELD_NUMBER = 2;
  private float latestProgressPercent_;
  /**
   * <code>float latest_progress_percent = 2;</code>
   */
  public float getLatestProgressPercent() {
    return latestProgressPercent_;
  }

  public static final int MESSAGE_FIELD_NUMBER = 3;
  private volatile java.lang.Object message_;
  /**
   * <code>string message = 3;</code>
   */
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>string message = 3;</code>
   */
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (updatesProcessed_ != 0) {
      output.writeInt32(1, updatesProcessed_);
    }
    if (latestProgressPercent_ != 0F) {
      output.writeFloat(2, latestProgressPercent_);
    }
    if (!getMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, message_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (updatesProcessed_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, updatesProcessed_);
    }
    if (latestProgressPercent_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, latestProgressPercent_);
    }
    if (!getMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, message_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.distilled.progress.UpdateSummaryResponse)) {
      return super.equals(obj);
    }
    com.distilled.progress.UpdateSummaryResponse other = (com.distilled.progress.UpdateSummaryResponse) obj;

    boolean result = true;
    result = result && (getUpdatesProcessed()
        == other.getUpdatesProcessed());
    result = result && (
        java.lang.Float.floatToIntBits(getLatestProgressPercent())
        == java.lang.Float.floatToIntBits(
            other.getLatestProgressPercent()));
    result = result && getMessage()
        .equals(other.getMessage());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + UPDATES_PROCESSED_FIELD_NUMBER;
    hash = (53 * hash) + getUpdatesProcessed();
    hash = (37 * hash) + LATEST_PROGRESS_PERCENT_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getLatestProgressPercent());
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.distilled.progress.UpdateSummaryResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.distilled.progress.UpdateSummaryResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.distilled.progress.UpdateSummaryResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.distilled.progress.UpdateSummaryResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.distilled.progress.UpdateSummaryResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.distilled.progress.UpdateSummaryResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.distilled.progress.UpdateSummaryResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.distilled.progress.UpdateSummaryResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.distilled.progress.UpdateSummaryResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.distilled.progress.UpdateSummaryResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.distilled.progress.UpdateSummaryResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.distilled.progress.UpdateSummaryResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.distilled.progress.UpdateSummaryResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Message sent from server back to client after processing the stream
   * </pre>
   *
   * Protobuf type {@code progress.UpdateSummaryResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:progress.UpdateSummaryResponse)
      com.distilled.progress.UpdateSummaryResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.distilled.progress.ProgressTrackerProto.internal_static_progress_UpdateSummaryResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.distilled.progress.ProgressTrackerProto.internal_static_progress_UpdateSummaryResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.distilled.progress.UpdateSummaryResponse.class, com.distilled.progress.UpdateSummaryResponse.Builder.class);
    }

    // Construct using com.distilled.progress.UpdateSummaryResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      updatesProcessed_ = 0;

      latestProgressPercent_ = 0F;

      message_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.distilled.progress.ProgressTrackerProto.internal_static_progress_UpdateSummaryResponse_descriptor;
    }

    @java.lang.Override
    public com.distilled.progress.UpdateSummaryResponse getDefaultInstanceForType() {
      return com.distilled.progress.UpdateSummaryResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.distilled.progress.UpdateSummaryResponse build() {
      com.distilled.progress.UpdateSummaryResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.distilled.progress.UpdateSummaryResponse buildPartial() {
      com.distilled.progress.UpdateSummaryResponse result = new com.distilled.progress.UpdateSummaryResponse(this);
      result.updatesProcessed_ = updatesProcessed_;
      result.latestProgressPercent_ = latestProgressPercent_;
      result.message_ = message_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.distilled.progress.UpdateSummaryResponse) {
        return mergeFrom((com.distilled.progress.UpdateSummaryResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.distilled.progress.UpdateSummaryResponse other) {
      if (other == com.distilled.progress.UpdateSummaryResponse.getDefaultInstance()) return this;
      if (other.getUpdatesProcessed() != 0) {
        setUpdatesProcessed(other.getUpdatesProcessed());
      }
      if (other.getLatestProgressPercent() != 0F) {
        setLatestProgressPercent(other.getLatestProgressPercent());
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.distilled.progress.UpdateSummaryResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.distilled.progress.UpdateSummaryResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int updatesProcessed_ ;
    /**
     * <code>int32 updates_processed = 1;</code>
     */
    public int getUpdatesProcessed() {
      return updatesProcessed_;
    }
    /**
     * <code>int32 updates_processed = 1;</code>
     */
    public Builder setUpdatesProcessed(int value) {
      
      updatesProcessed_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 updates_processed = 1;</code>
     */
    public Builder clearUpdatesProcessed() {
      
      updatesProcessed_ = 0;
      onChanged();
      return this;
    }

    private float latestProgressPercent_ ;
    /**
     * <code>float latest_progress_percent = 2;</code>
     */
    public float getLatestProgressPercent() {
      return latestProgressPercent_;
    }
    /**
     * <code>float latest_progress_percent = 2;</code>
     */
    public Builder setLatestProgressPercent(float value) {
      
      latestProgressPercent_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float latest_progress_percent = 2;</code>
     */
    public Builder clearLatestProgressPercent() {
      
      latestProgressPercent_ = 0F;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <code>string message = 3;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string message = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string message = 3;</code>
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string message = 3;</code>
     */
    public Builder clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string message = 3;</code>
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      message_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:progress.UpdateSummaryResponse)
  }

  // @@protoc_insertion_point(class_scope:progress.UpdateSummaryResponse)
  private static final com.distilled.progress.UpdateSummaryResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.distilled.progress.UpdateSummaryResponse();
  }

  public static com.distilled.progress.UpdateSummaryResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdateSummaryResponse>
      PARSER = new com.google.protobuf.AbstractParser<UpdateSummaryResponse>() {
    @java.lang.Override
    public UpdateSummaryResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UpdateSummaryResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UpdateSummaryResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UpdateSummaryResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.distilled.progress.UpdateSummaryResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

