// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: progress-tracker.proto

package com.distilled.progress;

public interface UpdateSummaryResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:progress.UpdateSummaryResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 updates_processed = 1;</code>
   */
  int getUpdatesProcessed();

  /**
   * <code>float latest_progress_percent = 2;</code>
   */
  float getLatestProgressPercent();

  /**
   * <code>string message = 3;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 3;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
