// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: course-catalog.proto

package com.distilled.coursecatalog;

public interface CourseRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:coursecatalog.CourseRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();
}
