// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: course-catalog.proto

package com.distilled.coursecatalog;

public final class CourseCatalogProto {
  private CourseCatalogProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coursecatalog_CourseRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coursecatalog_CourseRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coursecatalog_Course_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coursecatalog_Course_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coursecatalog_CourseList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coursecatalog_CourseList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coursecatalog_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coursecatalog_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024course-catalog.proto\022\rcoursecatalog\"\033\n" +
      "\rCourseRequest\022\n\n\002id\030\001 \001(\005\"f\n\006Course\022\n\n\002" +
      "id\030\001 \001(\005\022\r\n\005title\030\002 \001(\t\022\023\n\013description\030\003" +
      " \001(\t\022\022\n\ninstructor\030\004 \001(\t\022\030\n\020duration_min" +
      "utes\030\005 \001(\005\"4\n\nCourseList\022&\n\007courses\030\001 \003(" +
      "\0132\025.coursecatalog.Course\"\007\n\005Empty2\217\001\n\rCo" +
      "urseCatalog\022<\n\013ListCourses\022\024.coursecatal" +
      "og.Empty\032\025.coursecatalog.Course0\001\022@\n\tGet" +
      "Course\022\034.coursecatalog.CourseRequest\032\025.c" +
      "oursecatalog.CourseB3\n\033com.distilled.cou" +
      "rsecatalogB\022CourseCatalogProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_coursecatalog_CourseRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_coursecatalog_CourseRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coursecatalog_CourseRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_coursecatalog_Course_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_coursecatalog_Course_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coursecatalog_Course_descriptor,
        new java.lang.String[] { "Id", "Title", "Description", "Instructor", "DurationMinutes", });
    internal_static_coursecatalog_CourseList_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_coursecatalog_CourseList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coursecatalog_CourseList_descriptor,
        new java.lang.String[] { "Courses", });
    internal_static_coursecatalog_Empty_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_coursecatalog_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coursecatalog_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
