// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: course-catalog.proto

package com.distilled.coursecatalog;

public interface CourseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:coursecatalog.Course)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string title = 2;</code>
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 2;</code>
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string description = 3;</code>
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 3;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>string instructor = 4;</code>
   */
  java.lang.String getInstructor();
  /**
   * <code>string instructor = 4;</code>
   */
  com.google.protobuf.ByteString
      getInstructorBytes();

  /**
   * <code>int32 duration_minutes = 5;</code>
   */
  int getDurationMinutes();
}
