// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: course-catalog.proto

package com.distilled.coursecatalog;

/**
 * <pre>
 * A list of courses
 * </pre>
 *
 * Protobuf type {@code coursecatalog.CourseList}
 */
public  final class CourseList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:coursecatalog.CourseList)
    CourseListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CourseList.newBuilder() to construct.
  private CourseList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CourseList() {
    courses_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CourseList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              courses_ = new java.util.ArrayList<com.distilled.coursecatalog.Course>();
              mutable_bitField0_ |= 0x00000001;
            }
            courses_.add(
                input.readMessage(com.distilled.coursecatalog.Course.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        courses_ = java.util.Collections.unmodifiableList(courses_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.distilled.coursecatalog.CourseCatalogProto.internal_static_coursecatalog_CourseList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.distilled.coursecatalog.CourseCatalogProto.internal_static_coursecatalog_CourseList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.distilled.coursecatalog.CourseList.class, com.distilled.coursecatalog.CourseList.Builder.class);
  }

  public static final int COURSES_FIELD_NUMBER = 1;
  private java.util.List<com.distilled.coursecatalog.Course> courses_;
  /**
   * <code>repeated .coursecatalog.Course courses = 1;</code>
   */
  public java.util.List<com.distilled.coursecatalog.Course> getCoursesList() {
    return courses_;
  }
  /**
   * <code>repeated .coursecatalog.Course courses = 1;</code>
   */
  public java.util.List<? extends com.distilled.coursecatalog.CourseOrBuilder> 
      getCoursesOrBuilderList() {
    return courses_;
  }
  /**
   * <code>repeated .coursecatalog.Course courses = 1;</code>
   */
  public int getCoursesCount() {
    return courses_.size();
  }
  /**
   * <code>repeated .coursecatalog.Course courses = 1;</code>
   */
  public com.distilled.coursecatalog.Course getCourses(int index) {
    return courses_.get(index);
  }
  /**
   * <code>repeated .coursecatalog.Course courses = 1;</code>
   */
  public com.distilled.coursecatalog.CourseOrBuilder getCoursesOrBuilder(
      int index) {
    return courses_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < courses_.size(); i++) {
      output.writeMessage(1, courses_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < courses_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, courses_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.distilled.coursecatalog.CourseList)) {
      return super.equals(obj);
    }
    com.distilled.coursecatalog.CourseList other = (com.distilled.coursecatalog.CourseList) obj;

    boolean result = true;
    result = result && getCoursesList()
        .equals(other.getCoursesList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getCoursesCount() > 0) {
      hash = (37 * hash) + COURSES_FIELD_NUMBER;
      hash = (53 * hash) + getCoursesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.distilled.coursecatalog.CourseList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.distilled.coursecatalog.CourseList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.distilled.coursecatalog.CourseList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.distilled.coursecatalog.CourseList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.distilled.coursecatalog.CourseList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.distilled.coursecatalog.CourseList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.distilled.coursecatalog.CourseList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.distilled.coursecatalog.CourseList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.distilled.coursecatalog.CourseList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.distilled.coursecatalog.CourseList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.distilled.coursecatalog.CourseList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.distilled.coursecatalog.CourseList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.distilled.coursecatalog.CourseList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * A list of courses
   * </pre>
   *
   * Protobuf type {@code coursecatalog.CourseList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:coursecatalog.CourseList)
      com.distilled.coursecatalog.CourseListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.distilled.coursecatalog.CourseCatalogProto.internal_static_coursecatalog_CourseList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.distilled.coursecatalog.CourseCatalogProto.internal_static_coursecatalog_CourseList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.distilled.coursecatalog.CourseList.class, com.distilled.coursecatalog.CourseList.Builder.class);
    }

    // Construct using com.distilled.coursecatalog.CourseList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCoursesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (coursesBuilder_ == null) {
        courses_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        coursesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.distilled.coursecatalog.CourseCatalogProto.internal_static_coursecatalog_CourseList_descriptor;
    }

    @java.lang.Override
    public com.distilled.coursecatalog.CourseList getDefaultInstanceForType() {
      return com.distilled.coursecatalog.CourseList.getDefaultInstance();
    }

    @java.lang.Override
    public com.distilled.coursecatalog.CourseList build() {
      com.distilled.coursecatalog.CourseList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.distilled.coursecatalog.CourseList buildPartial() {
      com.distilled.coursecatalog.CourseList result = new com.distilled.coursecatalog.CourseList(this);
      int from_bitField0_ = bitField0_;
      if (coursesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          courses_ = java.util.Collections.unmodifiableList(courses_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.courses_ = courses_;
      } else {
        result.courses_ = coursesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.distilled.coursecatalog.CourseList) {
        return mergeFrom((com.distilled.coursecatalog.CourseList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.distilled.coursecatalog.CourseList other) {
      if (other == com.distilled.coursecatalog.CourseList.getDefaultInstance()) return this;
      if (coursesBuilder_ == null) {
        if (!other.courses_.isEmpty()) {
          if (courses_.isEmpty()) {
            courses_ = other.courses_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCoursesIsMutable();
            courses_.addAll(other.courses_);
          }
          onChanged();
        }
      } else {
        if (!other.courses_.isEmpty()) {
          if (coursesBuilder_.isEmpty()) {
            coursesBuilder_.dispose();
            coursesBuilder_ = null;
            courses_ = other.courses_;
            bitField0_ = (bitField0_ & ~0x00000001);
            coursesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCoursesFieldBuilder() : null;
          } else {
            coursesBuilder_.addAllMessages(other.courses_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.distilled.coursecatalog.CourseList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.distilled.coursecatalog.CourseList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.distilled.coursecatalog.Course> courses_ =
      java.util.Collections.emptyList();
    private void ensureCoursesIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        courses_ = new java.util.ArrayList<com.distilled.coursecatalog.Course>(courses_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.distilled.coursecatalog.Course, com.distilled.coursecatalog.Course.Builder, com.distilled.coursecatalog.CourseOrBuilder> coursesBuilder_;

    /**
     * <code>repeated .coursecatalog.Course courses = 1;</code>
     */
    public java.util.List<com.distilled.coursecatalog.Course> getCoursesList() {
      if (coursesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(courses_);
      } else {
        return coursesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .coursecatalog.Course courses = 1;</code>
     */
    public int getCoursesCount() {
      if (coursesBuilder_ == null) {
        return courses_.size();
      } else {
        return coursesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .coursecatalog.Course courses = 1;</code>
     */
    public com.distilled.coursecatalog.Course getCourses(int index) {
      if (coursesBuilder_ == null) {
        return courses_.get(index);
      } else {
        return coursesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .coursecatalog.Course courses = 1;</code>
     */
    public Builder setCourses(
        int index, com.distilled.coursecatalog.Course value) {
      if (coursesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCoursesIsMutable();
        courses_.set(index, value);
        onChanged();
      } else {
        coursesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .coursecatalog.Course courses = 1;</code>
     */
    public Builder setCourses(
        int index, com.distilled.coursecatalog.Course.Builder builderForValue) {
      if (coursesBuilder_ == null) {
        ensureCoursesIsMutable();
        courses_.set(index, builderForValue.build());
        onChanged();
      } else {
        coursesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .coursecatalog.Course courses = 1;</code>
     */
    public Builder addCourses(com.distilled.coursecatalog.Course value) {
      if (coursesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCoursesIsMutable();
        courses_.add(value);
        onChanged();
      } else {
        coursesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .coursecatalog.Course courses = 1;</code>
     */
    public Builder addCourses(
        int index, com.distilled.coursecatalog.Course value) {
      if (coursesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCoursesIsMutable();
        courses_.add(index, value);
        onChanged();
      } else {
        coursesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .coursecatalog.Course courses = 1;</code>
     */
    public Builder addCourses(
        com.distilled.coursecatalog.Course.Builder builderForValue) {
      if (coursesBuilder_ == null) {
        ensureCoursesIsMutable();
        courses_.add(builderForValue.build());
        onChanged();
      } else {
        coursesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .coursecatalog.Course courses = 1;</code>
     */
    public Builder addCourses(
        int index, com.distilled.coursecatalog.Course.Builder builderForValue) {
      if (coursesBuilder_ == null) {
        ensureCoursesIsMutable();
        courses_.add(index, builderForValue.build());
        onChanged();
      } else {
        coursesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .coursecatalog.Course courses = 1;</code>
     */
    public Builder addAllCourses(
        java.lang.Iterable<? extends com.distilled.coursecatalog.Course> values) {
      if (coursesBuilder_ == null) {
        ensureCoursesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, courses_);
        onChanged();
      } else {
        coursesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .coursecatalog.Course courses = 1;</code>
     */
    public Builder clearCourses() {
      if (coursesBuilder_ == null) {
        courses_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        coursesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .coursecatalog.Course courses = 1;</code>
     */
    public Builder removeCourses(int index) {
      if (coursesBuilder_ == null) {
        ensureCoursesIsMutable();
        courses_.remove(index);
        onChanged();
      } else {
        coursesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .coursecatalog.Course courses = 1;</code>
     */
    public com.distilled.coursecatalog.Course.Builder getCoursesBuilder(
        int index) {
      return getCoursesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .coursecatalog.Course courses = 1;</code>
     */
    public com.distilled.coursecatalog.CourseOrBuilder getCoursesOrBuilder(
        int index) {
      if (coursesBuilder_ == null) {
        return courses_.get(index);  } else {
        return coursesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .coursecatalog.Course courses = 1;</code>
     */
    public java.util.List<? extends com.distilled.coursecatalog.CourseOrBuilder> 
         getCoursesOrBuilderList() {
      if (coursesBuilder_ != null) {
        return coursesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(courses_);
      }
    }
    /**
     * <code>repeated .coursecatalog.Course courses = 1;</code>
     */
    public com.distilled.coursecatalog.Course.Builder addCoursesBuilder() {
      return getCoursesFieldBuilder().addBuilder(
          com.distilled.coursecatalog.Course.getDefaultInstance());
    }
    /**
     * <code>repeated .coursecatalog.Course courses = 1;</code>
     */
    public com.distilled.coursecatalog.Course.Builder addCoursesBuilder(
        int index) {
      return getCoursesFieldBuilder().addBuilder(
          index, com.distilled.coursecatalog.Course.getDefaultInstance());
    }
    /**
     * <code>repeated .coursecatalog.Course courses = 1;</code>
     */
    public java.util.List<com.distilled.coursecatalog.Course.Builder> 
         getCoursesBuilderList() {
      return getCoursesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.distilled.coursecatalog.Course, com.distilled.coursecatalog.Course.Builder, com.distilled.coursecatalog.CourseOrBuilder> 
        getCoursesFieldBuilder() {
      if (coursesBuilder_ == null) {
        coursesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.distilled.coursecatalog.Course, com.distilled.coursecatalog.Course.Builder, com.distilled.coursecatalog.CourseOrBuilder>(
                courses_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        courses_ = null;
      }
      return coursesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:coursecatalog.CourseList)
  }

  // @@protoc_insertion_point(class_scope:coursecatalog.CourseList)
  private static final com.distilled.coursecatalog.CourseList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.distilled.coursecatalog.CourseList();
  }

  public static com.distilled.coursecatalog.CourseList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CourseList>
      PARSER = new com.google.protobuf.AbstractParser<CourseList>() {
    @java.lang.Override
    public CourseList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CourseList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CourseList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CourseList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.distilled.coursecatalog.CourseList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

