// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: course-catalog.proto

package com.distilled.coursecatalog;

public interface CourseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:coursecatalog.CourseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .coursecatalog.Course courses = 1;</code>
   */
  java.util.List<com.distilled.coursecatalog.Course> 
      getCoursesList();
  /**
   * <code>repeated .coursecatalog.Course courses = 1;</code>
   */
  com.distilled.coursecatalog.Course getCourses(int index);
  /**
   * <code>repeated .coursecatalog.Course courses = 1;</code>
   */
  int getCoursesCount();
  /**
   * <code>repeated .coursecatalog.Course courses = 1;</code>
   */
  java.util.List<? extends com.distilled.coursecatalog.CourseOrBuilder> 
      getCoursesOrBuilderList();
  /**
   * <code>repeated .coursecatalog.Course courses = 1;</code>
   */
  com.distilled.coursecatalog.CourseOrBuilder getCoursesOrBuilder(
      int index);
}
