// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: course-catalog.proto

package com.distilled.coursecatalog;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:coursecatalog.Empty)
    com.google.protobuf.MessageOrBuilder {
}
