// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enrolment_service.proto

package com.distilled.enrolment;

public interface EnrolmentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:enrolment.EnrolmentResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
