// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enrolment_service.proto

package com.distilled.enrolment;

public interface EnrolmentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:enrolment.EnrolmentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string student_id = 1;</code>
   */
  java.lang.String getStudentId();
  /**
   * <code>string student_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getStudentIdBytes();

  /**
   * <code>string course_id = 2;</code>
   */
  java.lang.String getCourseId();
  /**
   * <code>string course_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getCourseIdBytes();

  /**
   * <code>string action = 3;</code>
   */
  java.lang.String getAction();
  /**
   * <code>string action = 3;</code>
   */
  com.google.protobuf.ByteString
      getActionBytes();
}
