// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enrolment_service.proto

package com.distilled.enrolment;

public final class EnrolmentServiceProto {
  private EnrolmentServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_enrolment_EnrolmentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_enrolment_EnrolmentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_enrolment_EnrolmentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_enrolment_EnrolmentResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027enrolment_service.proto\022\tenrolment\"I\n\020" +
      "EnrolmentRequest\022\022\n\nstudent_id\030\001 \001(\t\022\021\n\t" +
      "course_id\030\002 \001(\t\022\016\n\006action\030\003 \001(\t\"4\n\021Enrol" +
      "mentResponse\022\016\n\006status\030\001 \001(\t\022\017\n\007message\030" +
      "\002 \001(\t2d\n\020EnrolmentService\022P\n\017ManageEnrol" +
      "ment\022\033.enrolment.EnrolmentRequest\032\034.enro" +
      "lment.EnrolmentResponse(\0010\001B2\n\027com.disti" +
      "lled.enrolmentB\025EnrolmentServiceProtoP\001b" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_enrolment_EnrolmentRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_enrolment_EnrolmentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_enrolment_EnrolmentRequest_descriptor,
        new java.lang.String[] { "StudentId", "CourseId", "Action", });
    internal_static_enrolment_EnrolmentResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_enrolment_EnrolmentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_enrolment_EnrolmentResponse_descriptor,
        new java.lang.String[] { "Status", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
